[package]
name = "cybermd-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
cybermd-ast = { path = "../cybermd-ast" }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
